### ISSUE TITLE
AttributeError: module 'Tools' has no attribute 'color'

### ISSUE THREAD

**Issue by fatinghenji** [ogios/RainFlush#2]
```python3
PS D:\RainFlush> python d:/RainFlush/main.py -u T104755220086
Cookie保存路径: d:\RainFlush/usercookies/
当前pid: 49064
正在获取cookie...
未找到Cookie
onopen
Sending... 
Traceback (most recent call last):
  File "d:\RainFlush\main.py", line 24, in <module>
    main()
  File "C:\Users\FanTinghao\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\FanTinghao\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\FanTinghao\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\FanTinghao\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\RainFlush\main.py", line 12, in main
    cookie = us.getCookie()
  File "d:\RainFlush\USER.py", line 84, in getCookie

onmessage    self.login()
  File "d:\RainFlush\USER.py", line 195, in login

    Thread(target=self.sendSignData(60), daemon=True).start()
  File "d:\RainFlush\USER.py", line 108, in sendSignData
    print(f"\rwating... {Tools.color(str(i), 'green')}",  end="")
AttributeError: module 'Tools' has no attribute 'color'
```

**Comment by ogios** [comment]
非常抱歉，这个是我自己写的一个小工具py文件，这个刷课软件是我自己练手做的东西，疏忽了😭
现在已经上传，顺便我这里没试验过别的学校的，你那边如果可以使用的话告诉我一声
还有，第一次登录的话是不用输入学号的，会跳出二维码图片，使用微信扫码登录，登陆后cookies会以学号+.json的命名方式保存，到时候再使用 `-u 学号` 就可以不用重新微信扫码登录了

**Comment by fatinghenji** [comment]
同步源码后该问题解决。
> 顺便我这里没试验过别的学校的

直接使用似乎是直接进入长江雨课堂，而不是学校定制版本。请问网页链接在哪个文件中？

**Comment by ogios** [comment]
> 同步源码后该问题解决。
> > 顺便我这里没试验过别的学校的
> 直接使用似乎是直接进入长江雨课堂，而不是学校定制版本。请问网页链接在哪个文件中？

在RUN.py中的run类中。我没写统一修改的方法，可以自行修改构造函数里的url。
但是鉴于我只用过也只能用长江雨课堂，不清楚是否在请求内容和方式上有所差别，可以试试直接修改域名，说不定可以用

**Comment by fatinghenji** [comment]
> 可以试试直接修改域名，说不定可以用

修改域名后：
```python3
选择课程:
0. {'classroom_id': 14544534, 'uv': 3357, 'name': '综合素质教育（下）'}
1. {'classroom_id': 14544543, 'uv': 3357, 'name': '科研设计'}
2. {'classroom_id': 14544541, 'uv': 3357, 'name': '住院医师规范化培训公共课程（上）'}
3. {'classroom_id': 14544529, 'uv': 3357, 'name': '公共英语（上）'}
4. {'classroom_id': 14544530, 'uv': 3357, 'name': '公共英语（下）'}
5. {'classroom_id': 14544531, 'uv': 3357, 'name': '中国特色社会主义理论与实践研究'}
6. {'classroom_id': 14544532, 'uv': 3357, 'name': '自然辩证法概论'}
7. {'classroom_id': 14544533, 'uv': 3357, 'name': '综合素质教育（上）'}
8. {'classroom_id': 14544540, 'uv': 3357, 'name': '文献信息检索与应用'}
9. {'classroom_id': 14544535, 'uv': 3357, 'name': '学术活动和实践创新'}
10. {'classroom_id': 14544536, 'uv': 3357, 'name': '医学统计学'}
11. {'classroom_id': 14544537, 'uv': 3357, 'name': '循证医学'}
12. {'classroom_id': 14544538, 'uv': 3357, 'name': '专业理论与技术讲座（上）'}
13. {'classroom_id': 14544539, 'uv': 3357, 'name': '专业理论与技术讲座（下）'}
14. {'classroom_id': 706081, 'uv': 0, 'name': '寄生虫'}
15. {'classroom_id': 673830, 'uv': 0, 'name': '寄生虫学'}
16. {'classroom_id': 337139, 'uv': 0, 'name': '医学遗传学'}
>>> 5
中国特色社会主义理论与实践研究
学习日志分段: []
```
并没有继续

**Comment by ogios** [comment]
> 并没有继续

可以将cookie文件与域名发给我么
2134692955@qq.com
我今晚会查看是什么原因并试着解决

**Comment by fatinghenji** [comment]
已发送

**Comment by ogios** [comment]
> 已发送

已接受

**Comment by ogios** [comment]
已解决，学校定制的雨课堂有蛮多不一样的
可以查看 ` 综合素质教育(下) ` 这个已经刷了两节课了
获取视频属性和已完成的视频的接口变了，请求方式和参数也变了。现在可以刷视频，只是阅读和测试作业的项目需要手动去做
你可以使用的脚本在单独分出来的 `hb` 文件夹里，使用方式和原来相同
我会将你的cookie用qq邮箱发回去，或者你重新登录，都可以

**Comment by fatinghenji** [comment]
> 你可以使用的脚本在单独分出来的 hb 文件夹里，使用方式和原来相同

- 脚本文件夹忘了塞`Tools.py`。
  - 手动放入后，该问题可以解决
- `hb`文件夹中相关py文件是否还需要做网址替换？在不做替换的情况下出现以下问题
```python
error
'expire_seconds'
<RequestsCookieJar[<Cookie csrftoken=f3fzOWfHsjqNtMmJADYbeBEn47UXHWsP for changjiang.yuketang.cn/>, <Cookie django_language=zh-cn for changjiang.yuketang.cn/>, <Cookie login_type=WX for changjiang.yuketang.cn/>, <Cookie sessionid=tmnp8f49y43606hzc86e0wvcprgulx6a for changjiang.yuketang.cn/>]>
请求课程失败 - 未知错误
{"errcode":401002,"errmsg":"Cookie has no sessionid"}
```
- 手动替换`changjiang.yuketang.cn`为`henutdxl.yuketang.cn`后，脚本可以读取到cookie并运行，但出现新问题，脚本中显示播放过的视频课程，在网页中依旧显示未播放。

**Comment by ogios** [comment]
对于第二个问题，是登录问题(session过时失效了或者别的原因)，可以通过重新登录(命令函参数取消 `-u` 后可以重新扫码登录)解决。
对于第三个问题，我记得需要更换的url都已经更换。
关于有进度但仍显示无法观看的问题，对于 `综合素质教育` 可以使用，但在我手动查看你的 `中国特色社会主义理论与实践研究` 课程时，发现了和曾经一样的问题：其实是已经刷完了，但是视频观看状态没被激活，可以通过手动点进去视频一下就可以激活观看状态100%。
我在请求刷视频的开头加入了一串心跳数据，现在可以自动激活了，不用手动去管

**Comment by ogios** [comment]
我会将cookie通过qq邮箱发给你

**Comment by fatinghenji** [comment]
问题解决，感谢开发者耐心解答
